name: hmatuschek-radio-anytone-gadget
version: git
grade: stable

summary: Gadget snap to provide access to serial port of AnyTone radios.
description: |
  Just a tiny gadget snap to provide a defined serial interface to AnyTone radios.
  They will be bound to /dev/serial-port-anytone.

confinement: strict
base: core18

slots:
  hmatuschek-radio-anytone-gadget:
    interface: serial-port
    usb-vendor: 0x28e9
    usb-product: 0x018a
    path: /dev/serial-port-anytone


parts:
  hmatuschek-radio-anytone-gadget:
    plugin: nil
    source: https://github.com/hmatuschek/qdmr.git
    source-type: git
    source-branch: "anytone-gadget"
