name: opengd77-gadget
version: git
grade: stable

summary: Gadget snap to provide access to serial port of OpenGD77 radios.
description: |
  Just a tiny gadget snap to provide a defined serial interface to radios running
  the OpenGD77 firmware. They will be bound to /dev/serial-port-anytone

confinement: strict
base: core18

slots:
  opengd77:
    interface: serial-port
    usb-vendor: 0x1fc9
    usb-product: 0x0094
    path: /dev/serial-port-opengd77
#  anytone:
#    interface: serial-port
#    usb-vendor: 0x28e9
#    usb-product: 0x018a
#    path: /dev/serial-port-anytone

